Added multiple flags to moodle
ouspg/ainigma pull request #20
Opened 2024-10-11 15:38 UTC by PootisHunter

Closes #17 

-Added multiple flag support for answers and a test that shows functionality (test_multiple_flags)

- Current separator for flags:  ";"

- Using itertools crate to implement combinations and permutations for flags

Generating answers for 3 flags currently adds total 6+12+12 = 30 answers
- 6 answers for 33 fraction ( 3 flag_string and 3 encase_flag answers)
- 12 answers for 67 fraction ( 6 flag_string and 6 encase_flag answers)
- 12 answers for 100 fraction  ( 6 flag_string and 6 encase_flag answers)

2024-10-16 13:59 UTC, Nicceboy requested changes

2024-10-16 13:59 UTC, Nicceboy commented on src/moodle.rs
> +mod tests {
I think we might need to add at least one test e.g. with 3 flags to guarantee that flags work as intended and produce the output deterministically and the final exam has exactly the amount of correct unique permutations (no duplicates, for example).

2024-10-16 13:59 UTC, Nicceboy commented on src/moodle.rs
> +mod tests {
We also need a test when student submits 1, 2 or 3 flags and see that all are accepted if the flag is correct.

2024-10-16 13:59 UTC, Nicceboy commented on src/moodle.rs
> +                    process_multiple_flags(item.flags.clone(), ";")
We can make separator as constant in this file and pass it as reference for this. I believe space is better separator in this context (for readability and clarity). Flags should never have spaces in them, while other characters are possible.

2024-10-16 13:59 UTC, Nicceboy commented on src/moodle.rs
> +                let points = ((r as f64 / total_flags as f64) * 100.0).round() as u8;
We need to round with 4 decimals (at least that is how Moodle does it internally)

2024-10-16 14:02 UTC, Nicceboy commented on src/moodle.rs
> +mod tests {
These tests can be mainly implemented with constructed strings

2024-10-23 11:45 UTC, PootisHunter commented on src/moodle.rs
> +                let points = ((r as f64 / total_flags as f64) * 100.0).round() as u8;
What this code does is give answer fraction value between 0-100 depending how many correct flags

1 / 3 correct flags giving 33
2 / 3 correct flags giving 67
3 / 3 correct flags giving 100 and etc.

2024-10-23 11:53 UTC, PootisHunter commented on src/moodle.rs
> +                    process_multiple_flags(item.flags.clone(), ";")
changed separator to " "

2024-10-23 12:17 UTC, PootisHunter commented on src/moodle.rs
> +mod tests {
changed tests to check 1, 2, 3 flag answers and make sure they contain

- appropriate fraction values depending on the amount of flags
- contained appropriate amount of flag_prefixes for the fraction value

2024-10-28 10:58 UTC, Nicceboy approved these changes

2024-10-28 10:58 UTC, Nicceboy commented on src/moodle.rs
> +                let points = ((r as f64 / total_flags as f64) * 100.0).round() as u8;
Maybe we can test it against Moodle with a real exam and see if works, and address it later if it does not like the fractions on some cases.

2024-10-28 10:58 UTC, Nicceboy commented on src/moodle.rs
> +}
OK. This does not ensure that there are no duplicates but maybe we can trust the logic of itertools. However, tests should always ensure that if we made changes in the code, the end functionality remains and we get confidence that system still works, so tests should be strict enough.

2024-10-28 10:58 UTC, merged